### ISSUE TITLE
Code deadlock due to synchronized blocks

### ISSUE THREAD

**Issue by narras-oss** [aws/aws-xray-sdk-java#303] opened 2021-09-29 01:11 UTC
We noticed a code deadlock within few hours f upgrading to Xray SDK version 2.9.1 from 2.8.0 at these stack trace locations.
We reverted back to 2.8.0 since the synchronized() blocks weren't there in EntityImpl in version 2.8.0.

Thread 1:
java.lang.Thread.State: BLOCKED (on object monitor)
at com.amazonaws.xray.entities.SegmentImpl.isSampled(SegmentImpl.java:91)
- waiting to lock <0x000000008527a6b8> (a java.lang.Object)
at com.amazonaws.xray.strategy.DefaultStreamingStrategy.requiresStreaming(DefaultStreamingStrategy.java:70)
at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:81)
at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:628)
at com.amazonaws.xray.entities.SubsegmentImpl.close(SubsegmentImpl.java:167)
- locked <0x000000008527a6a8> (a java.lang.Object)

Thread2:
java.lang.Thread.State: BLOCKED (on object monitor)
at com.amazonaws.xray.entities.EntityImpl.getId(EntityImpl.java:237)
- waiting to lock <0x000000008527a6a8> (a java.lang.Object)
at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.12/Unknown Source)
at java.lang.reflect.Method.invoke(java.base@11.0.12/Unknown Source)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
at com.amazonaws.xray.entities.EntityImpl.serialize(EntityImpl.java:749)
- locked <0x000000008527a6b8> (a java.lang.Object)
at com.amazonaws.xray.emitters.UDPEmitter.sendSegment(UDPEmitter.java:85)
at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:195)
at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:79)
at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:628)
at com.amazonaws.xray.entities.SubsegmentImpl.close(SubsegmentImpl.java:167)
- locked <0x00000000852824c8> (a java.lang.Object)

This issue is serious since it deadlocked the forkoinpool threads we have (only a few) and causes application to become unresponsive

**Comment by willarmiros** [comment] 2021-09-29 17:23
Thanks for raising this @narras-oss - we will take a look.

@anuraaga It looks like this could be related to #279. Would you be able to investigate if that could cause this deadlock?

**Comment by hden** [comment] 2021-12-12 01:57
I can confirm that a deadlock can still happen in 2.10.0.

**Comment by iwataka** [comment] 2022-07-27 12:48
Any update on this issue?

I used v2.11.1 and faced the same issue.
I was investigating for a while and guess that the below things cause this issue.

1. SubsegmentImpl#end method acquire the lock of itself and then acquire the parentSegment's lock.
2. SegmentImpl#serialize method (defined in EntityImpl class) acquire the lock of itself and then acquire the subsegments' lock (ex. by calling subsegment's getId method which mentioned in the above comment).
3. When multiple threads execute both of AWSXrayRecorder#endSegment (which calls SegmentImpl#serialize internally) and AWSXrayRecorder#endSubsegment (which calls SubsegmentImpl#end internally) at the same time, deadlock may occur because each order of lock acquisition is opposite each other.

Possible solution for this issue would be to acquire locks in the same order.
For example, update SubsegmentImpl#end like below and make it acquire locks in the order from parent to subsegments.
(Off course `parentSegment.lock` is not accessible and we should make it accessible in advance)

```java
    @Override
    public boolean end() {
        synchronized (this.parentSegment.lock) {
            synchronized (lock) {
                ...
            }
        }
    }
```

**Comment by nluk** [comment] 2022-11-15 15:01
Hi @willarmiros, we still experience deadlocks on v2.12.0 (so after the synchronization changes revert). Thread dump:
```"sdk-async-response-4-3292" #35204 daemon prio=5 os_prio=0 cpu=206.78ms elapsed=9728.07s tid=0x00007fbf2c08c000 nid=0x856c waiting for monitor entry  [0x00007fbf296e6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.amazonaws.xray.entities.EntityImpl.getId(EntityImpl.java:240)
	- waiting to lock <0x000000078663d378> (a java.lang.Object)
	at jdk.internal.reflect.GeneratedMethodAccessor984.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.14/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.14/Method.java:566)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
	at com.amazonaws.xray.entities.EntityImpl.serialize(EntityImpl.java:746)
	- locked <0x000000078663e880> (a java.lang.Object)
	at com.amazonaws.xray.emitters.UDPEmitter.sendSegment(UDPEmitter.java:85)
	at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:195)
	at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:588)
	at com.amazonaws.xray.interceptors.TracingInterceptor.afterExecution(TracingInterceptor.java:288)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$afterExecution$11(ExecutionInterceptorChain.java:192)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain$$Lambda$1238/0x0000000840ae3440.accept(Unknown Source)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.reverseForEach(ExecutionInterceptorChain.java:234)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.afterExecution(ExecutionInterceptorChain.java:192)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AfterExecutionInterceptorsStage.execute(AfterExecutionInterceptorsStage.java:26)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$AsyncRequestPipelineWrapper.lambda$execute$0(RequestPipelineBuilder.java:229)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$AsyncRequestPipelineWrapper$$Lambda$5216/0x0000000841c40840.apply(Unknown Source)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeFunction$3(FunctionalUtils.java:92)
	at software.amazon.awssdk.utils.FunctionalUtils$$Lambda$5217/0x0000000841c40c40.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(java.base@11.0.14/CompletableFuture.java:642)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.14/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.14/CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:174)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor$$Lambda$5215/0x0000000841c40440.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.14/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.14/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.14/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.14/CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:106)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$$Lambda$5213/0x0000000841c34440.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.14/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.14/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.14/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.14/CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:207)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$$Lambda$5212/0x0000000841c34040.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.14/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.14/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture$Completion.run(java.base@11.0.14/CompletableFuture.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.14/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.14/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.14/Thread.java:829)
```
```"sdk-async-response-4-3299" #35211 daemon prio=5 os_prio=0 cpu=208.77ms elapsed=9726.28s tid=0x00007fbf2c050000 nid=0x8573 waiting for monitor entry  [0x00007fbfd4bde000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.amazonaws.xray.entities.EntityImpl.decrementReferenceCount(EntityImpl.java:681)
	- waiting to lock <0x000000078663e880> (a java.lang.Object)
	at com.amazonaws.xray.entities.SubsegmentImpl.end(SubsegmentImpl.java:69)
	- locked <0x000000078663d378> (a java.lang.Object)
	at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:578)
	at com.amazonaws.xray.interceptors.TracingInterceptor.afterExecution(TracingInterceptor.java:288)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$afterExecution$11(ExecutionInterceptorChain.java:192)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain$$Lambda$1238/0x0000000840ae3440.accept(Unknown Source)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.reverseForEach(ExecutionInterceptorChain.java:234)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.afterExecution(ExecutionInterceptorChain.java:192)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AfterExecutionInterceptorsStage.execute(AfterExecutionInterceptorsStage.java:26)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$AsyncRequestPipelineWrapper.lambda$execute$0(RequestPipelineBuilder.java:229)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$AsyncRequestPipelineWrapper$$Lambda$5216/0x0000000841c40840.apply(Unknown Source)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeFunction$3(FunctionalUtils.java:92)
	at software.amazon.awssdk.utils.FunctionalUtils$$Lambda$5217/0x0000000841c40c40.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(java.base@11.0.14/CompletableFuture.java:642)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.14/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.14/CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:174)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor$$Lambda$5215/0x0000000841c40440.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.14/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.14/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.14/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.14/CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:106)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$$Lambda$5213/0x0000000841c34440.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.14/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.14/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.14/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.14/CompletableFuture.java:2073)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:207)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$$Lambda$5212/0x0000000841c34040.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.14/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.14/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture$Completion.run(java.base@11.0.14/CompletableFuture.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.14/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.14/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.14/Thread.java:829)
```

**Comment by iwataka** [comment] 2022-11-19 15:15
This issue seems to be resolved in v2.12.0 in my machine.

According to @nluk 's thread dump, maybe you refer to v2.11.2 or older version unintentionally.
The reason for it is that there's a lock statement at that line (`EntityImpl.java:240`) in v2.11.2 or older, but no statement (but just `@Override` annotation) there in 2.12.0.
I think this kind of thread dump can't be shown in v2.12.0.

https://github.com/aws/aws-xray-sdk-java/blob/v2.11.2/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/EntityImpl.java#L240

https://github.com/aws/aws-xray-sdk-java/blob/v2.12.0/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/EntityImpl.java#L240

**Comment by narras-oss** [comment] 2022-11-21 01:11
I filed this issue on the older version and the stack trace corresponds to that. So it is possible the line numbers have changed in latest version of code since the code evolved. 
We noticed this on production (not using a reproduction) and it caused the few threads in a fork join executor to deadlock and service became unresponsive (so a serious issue).

@iwataka From your comments it is not clear whether the locks have been completely removed and hence the possibility of a deadlock has been removed or if it is still possible the code will deadlock and the line numbers just changed in the stack trace in the newer code.

**Comment by willarmiros** [comment] 2022-11-23 16:18
Great to hear this was resolved for you @iwataka! Agreed with the assessment that it's possible @nluk is still accidentally using an older version based on stack trace, if there is a way to get an updated stack trace with v2.12.0 (if the deadlock is still somehow occurring) that would be helpful!

@narras-oss have you upgraded to v2.12.0 to see if it resolved your deadlocks yet?

**Comment by narras-oss** [comment] 2022-11-23 17:23
@willarmiros  not yet. I will post here in a week or two once we upgrade and monitor for the deadlock

**Comment by narras-oss** [comment] 2022-12-20 21:33
Our team did not get a chance to upgrade and test this yet. Please feel free to close the issue since the locks were replaced with ConcurrentHashMap.

**Comment by nluk** [comment] 2022-12-22 08:28
@willarmiros  I can confirm that v2.12.0 works for us, no issues since. The previous stacktrace was indeed from before the upgrade, sorry for the mislead.

**Comment by willarmiros** [comment] 2022-12-22 17:01
Thanks for the update @nluk! Closing out this issue then

**Closed by willarmiros** 2022-12-22 17:01 UTC
Labels: bug
