### ISSUE TITLE
CentralizedSamplingStrategy constructs a new recorder at each invocation when no service type in sampling request

### ISSUE THREAD

**Issue by aapolait** [aws/aws-xray-sdk-java#46] opened 2018-12-10 10:33 UTC
When an `AWSXRayRecorder` is built without plugins and without explicitly setting the origin, `CentralizedSamplingStrategy#shouldTrace` will be called with a sampling request that doesn't have a service type. It has the following fallback:

https://github.com/aws/aws-xray-sdk-java/blob/9fb8e151ab77f75f7a4f2544c1e903365ea5b569/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/sampling/CentralizedSamplingStrategy.java#L63-L65

Not only does the fallback construct a new recorder at each invocation, but it also ends up being wasted work because the result of `defaultRecorder()` won't have any plugins either.

I'd be happy to submit a fix, but don't know what would be your preferred approach:

1. Just remove the fallback since it isn't working anyway?
2. Make `CentralizedSamplingStrategy` or `AWSXRayRecorderBuilder` have a list of default plugins that will be queried for origin when the recorder doesn't have an origin? (Though it looks like only `EC2Plugin` could be on the list since `ECSPlugin` always "matches" and `ElasticBeanstalkPlugin` is too noisy when it doesn't.)
3. Something else?

**Comment by chrisradek** [comment] 2018-12-29 00:40
@aapolait 
Thanks for bringing this up! I'll do some digging to see if this ever worked and what the expected behavior should be.

**Comment by chrisradek** [comment] 2019-04-25 23:33
Closing since this was released in version 2.2.x.

**Closed by chrisradek** 2019-04-25 23:33 UTC
Labels: bug
