### ISSUE TITLE
Easier way to enable including SQL query in subsegment with 

### ISSUE THREAD

**Issue by swanandvk** [aws/aws-xray-sdk-java#257] opened 2021-01-29 07:50 UTC
Using `aws-xray-recorder-sdk-sql` By default it does not include sql statement in traces , if there is any easier way to enable it 
eg:
`TracingConnection.decorate(dataSource.connection).includeQuery(true)`

Or is there any way present currently which can be used generically with the SDK apart from manually adding the subsegment

**Comment by willarmiros** [comment] 2021-01-29 19:13
This behavior is not yet supported, but we'd be open to a PR that does capture the SQL query string when possible on an opt-in basis. I'm going to close this as a duplicate of #28, which requests the same thing.

**Closed by willarmiros** 2021-01-29 19:13 UTC
